# NumPy Essentials Practice Exercises Overview:
Time to test the knowledge on NumPy. Lets start with simple task and move on to more challenging ones!<br>
**Good Luck**<br>

&#9758; *Please note, there are several ways to get the required output, so your code could be different then what is provided in this notebook. <br>As long as you are getting the tasks done, it is fine at this stage. *

**1. What is the major difference between "`Vector`" and "`Matrix`"?**

In [1]:
# A vector is a one-dimensional array (like a list of values), while a matrix is a two-dimensional array (like a grid with rows and columns).
# Example:
import numpy as np
vector = np.array([1, 2, 3])
matrix = np.array([[1, 2], [3, 4]])
print("Vector:", vector)
print("Matrix:\n", matrix)

Vector: [1 2 3]
Matrix:
 [[1 2]
 [3 4]]


**2. How to import `NumPy` library?** 

In [3]:
import numpy as np 

**3. Convert the given Python list into NumPy array and check its data type**

In [6]:
list_1 = [1,2,3,4,5]

In [7]:
# To avoid overwriting the output, please code here 
array_1 = np.array(list_1)
print("Numpy Array:", array_1)


Numpy Array: [1 2 3 4 5]


In [8]:
print("Datatype:", array_1.dtype)

Datatype: int64


**4. Generate `array [0,1,2,3,4,5]` using NumPy built-in function, `arange()`**

In [4]:
# To avoid overwriting the output, please code here 
arr = np.arange(6)
print(arr)

[0 1 2 3 4 5]


[0 1 2 3 4 5]


**5. Generate an `array of "5" zeros` **

In [78]:
# To avoid overwriting the output, please code here 
zeros_array = np.zeros(5)
print(repr(zeros_array))

array([0., 0., 0., 0., 0.])


array([ 0.,  0.,  0.,  0.,  0.])

**6. Generate the following `matrix`.**

In [7]:
# To avoid overwriting the output, please code here 
matrix = np.zeros((3, 4))
print(repr(matrix))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])


array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

**7. Generate** `[1.,1.,1.,1.,1.]` **using NumPy built-in function?**

In [77]:
# To avoid overwriting the output, please code here 
ones_array = np.ones(5)
print(repr(ones_array))

array([1., 1., 1., 1., 1.])


array( [1. 1. 1. 1. 1.] )


**8. Generate an array of "5" tens.**

In [76]:
# To avoid overwriting the output, please code here 
tens_array = np.ones(5) * 10
print(repr(tens_array))

array([10., 10., 10., 10., 10.])


array([10., 10., 10., 10., 10.])

**9. Use `arange()` to generate an array of even numbers between 50 and 100.**<br>
*50 and 100 are not included*

In [75]:
# To avoid overwriting the output, please code here 
even_numbers = np.arange(50, 100, 2)
print(repr(even_numbers))

array([50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82,
       84, 86, 88, 90, 92, 94, 96, 98])


array([52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84,
       86, 88, 90, 92, 94, 96, 98])

**10. Generate an array of 10 linearly spaced points between 0 and 1.**<br>
**Output step size as well?**

In [74]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0, 1, 10)
step_size = arr[1] - arr[0]

print("array(",arr, step_size,")")

array( [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ] 0.1111111111111111 )


(array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  0.44444444,
         0.55555556,  0.66666667,  0.77777778,  0.88888889,  1.        ]),
 0.1111111111111111)

**11. Perform the following tasks:**
* Generate a **`vector array of 25`** numbers using **`arange()`**
* write a code to convert the vector array into **`2-D matrix using reshape`**
* can we use **`shape`** instead of reshape as well?

In [71]:
# To avoid overwriting the output, please code here 
vector = np.arange(25)
print(repr(vector))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])


In [22]:
# Generating vector array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
# To avoid overwriting the output, please code here 
arr = np.arange(25).reshape(5, 5)
print(repr(arr))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


In [24]:
# reshape to convert into 2-d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [56]:
# To avoid overwriting the output, please code here 
arr = np.arange(25)
arr.shape = (5, 5)
print(repr(arr))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


In [26]:
# Using shape

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**12. Please generate the following matrix.**

In [57]:
# To avoid overwriting the output, please code here 
arr = np.arange(0.1, 2.6, 0.1).reshape(5, 5)
print(repr(arr))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])


array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ],
       [2.1, 2.2, 2.3, 2.4, 2.5]])

**13. Write a code to generate the output below, use "`linspace()`" and "`print()`"**

In [59]:
# To avoid overwriting the output, please code here 
arr = np.linspace(0, 24, 25, dtype=int).reshape(5, 5)
print(repr(arr))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**14. What is the main difference between `linspace()` and `arange()`?**

In [60]:
# Please consult the lectures. 
# arange() takes 3rd argument as step size.
# linspace() take 3rd argument as no of point we want.

#`linspace() generates a specified number of evenly spaced points between start and stop (inclusive), while arange() generates values spaced by a fixed step size between start and stop (exclusive). 

print("linspace Example: ", np.linspace(0, 1, 5))  

print("arange Example: " ,np.arange(0, 1, 0.25))  

linspace Example:  [0.   0.25 0.5  0.75 1.  ]
arange Example:  [0.   0.25 0.5  0.75]


**15. How to generate a single random integer number using NumPy built-in function?**

In [69]:
# To avoid overwriting the output, please code here 
random_int = np.random.randint(low=0, high=100)
print(random_int)

79


54


**16. Write a code to generate a 7x5 matrix of 35 random numbers? use rand here** <br>
*Notice, there are no ( ) in the output matrix!*

In [64]:
# To avoid overwriting the output, please code here 
arr = np.random.rand(7, 5)
print(arr)

[[0.72692935 0.20810592 0.94456334 0.95218776 0.45671706]
 [0.89792935 0.57942726 0.87659248 0.52083611 0.41921212]
 [0.59580787 0.45640779 0.82571998 0.5273095  0.01067191]
 [0.77059333 0.64376585 0.85548361 0.73850044 0.60021831]
 [0.15809913 0.13569343 0.46344709 0.10324368 0.6573341 ]
 [0.76783534 0.85282817 0.67021179 0.46849433 0.43801571]
 [0.81871986 0.76006219 0.98900317 0.8578218  0.88994952]]


[[ 0.99598801  0.07546767  0.17484793  0.25229956  0.4693597 ]
 [ 0.5591561   0.5007227   0.93630239  0.48747691  0.78658124]
 [ 0.98923838  0.04124599  0.71326198  0.51252888  0.36130539]
 [ 0.11558779  0.52914213  0.31134907  0.8047612   0.25759207]
 [ 0.87331331  0.77104413  0.960445    0.1732589   0.83339285]
 [ 0.99839604  0.78268012  0.66487603  0.14509928  0.05670129]
 [ 0.15932364  0.848172    0.51343887  0.06309231  0.29250649]]


**17. Generate the following matrix using NumPy's built-in method for identity matrix.**

In [70]:
# To avoid overwriting the output, please code here
matrix = 5 * np.eye(5)
print(repr(matrix))

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])


array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### You must be feeling comfortable using NumPy now!
# Great Job and Good Luck 